apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q9wa9k46j-go
  janus-idp.io/tekton: q9wa9k46j-go
  backstage.io/kubernetes-id: q9wa9k46j-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q9wa9k46j-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
